### ISSUE TITLE
NoMethodError at / undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by doronbehar** [theunraveler/taskwarrior-web#139]
So today I wanted to test drive the application. I cloned the repo, Ran `make run`, and got the following error when opening `http://localhost:5678/` in the browser:

```
 application error
NoMethodError at /
undefined method `length' for nil:NilClass

    file: delimiter.rb location: parse line: 192 

```

This is copied from the web interface, I'd have liked to print a full backtrace but I'm not sure where I'm supposed to get it from, as the web interface doesn't seem to provide a plaintext version of it..

I read at #100 that taskwarrior needs to be installed. Is it installed in the docker image? Will running the application with this method will use my `~/.taskrc` and it's included files?

**Comment by jwynn6** [comment]
bumped, same issue.

**Comment by zesaver** [comment]
I have the same

**Comment by bitroniq** [comment]
Same here, even on empty `.task/`

**Comment by bitroniq** [comment]
I found a root cause of this bug - it is due to wrong docker volume or empty `~/.task` and/or `~/.taskrc` - Especially when using taskwarrior-web in a docker.



This is the `docker-compose.yml` that works for me I displays correctly the tasks:

`cat docker-compose.yml`
```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5678:5678
    deploy:
      restart_policy:
        condition: always
    volumes:
    - ~/.task:/root/.task
  ```
